---
roles:
  - name: buluma.bootstrap
  - name: buluma.buildtools
  - name: buluma.core_dependencies
  - name: buluma.systemd
  - name: buluma.python_pip
  - name: buluma.sysctl
collections:
  - name: community.rabbitmq
  - name: community.docker
  - name: community.general
