---

- name: arg_spec | Verify vars needed for this task file are present when included
  ansible.builtin.validate_argument_spec:
    argument_spec: '{{ required_data }}'
  vars:
    required_data:
      # unlike spec file, just put the options in directly
      stuff:
        description: Stuff
        type: str
        choices: ['who', 'knows', 'what']
        default: what
      but:
        description: I guess we need one
        type: str
        required: true
