---
- name: command_collector | collect commands
  block:
    - name: command_collector | Run command {{ object }}
      ansible.builtin.command:
        cmd: "{{ object }}"
      changed_when: no
      register: forensics_run_command

    - name: command_collector | Save output to {{ object | replace(' ', '-') }}.txt
      ansible.builtin.copy:
        content: "{{ forensics_run_command.stdout }}"
        dest: "{{ forensics_local_storage_path }}/{{ inventory_hostname_short }}/{{ object | replace(' ', '-') }}.txt"
        mode: "0640"
      delegate_to: localhost
      changed_when: no
  rescue:
    - name: command_collector | Rescue when command failed.
      ansible.builtin.debug:
        msg: "Could not collect command {{ object }}"
