---

- name: core | Install core packages
  ansible.builtin.package:
    name: "{{ core_dependencies }}"
    state: present
    update_cache: yes
  notify:
    - Gather facts

- name: core | Reset connetion
  ansible.builtin.meta: reset_connection

- name: core | Try to install pip packages
  ansible.builtin.pip:
    name: "{{ core_dependencies_pip_packages }}"
    state: present
  failed_when: no
  notify:
    - Gather facts

- name: core | Flush handlers
  ansible.builtin.meta: flush_handlers
