---
# tasks file for ansible-role-testing
- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- include: ping.yml
  tags:
    - ping

# Passed
# - name: Asynchronous yum task
#   ansible.builtin.yum:
#     name: docker-io
#     state: present
#   async: 1000
#   poll: 0
#   register: yum_sleeper
#
# - name: Wait for asynchronous job to end
#   ansible.builtin.async_status:
#     jid: '{{ yum_sleeper.ansible_job_id }}'
#   register: job_result
#   until: job_result.finished
#   retries: 100
#   delay: 10

- name: Add repository
  ansible.builtin.yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Add multiple repositories into the same file (1/2)
  ansible.builtin.yum_repository:
    name: epel
    description: EPEL YUM repo
    file: external_repos
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no

- name: Add multiple repositories into the same file (2/2)
  ansible.builtin.yum_repository:
    name: rpmforge
    description: RPMforge YUM repo
    file: external_repos
    baseurl: http://apt.sw.be/redhat/el7/en/$basearch/rpmforge
    mirrorlist: http://mirrorlist.repoforge.org/el7/mirrors-rpmforge
    enabled: no
# Passed

# - include: package.yml
#   tags:
#     - package

# - name: Install pexpect python package
#   pip:
#     name: pexpect
#
# # Does not support pip3
# - name: Case insensitive password string match
#   ansible.builtin.expect:
#     command: passwd root
#     responses:
#       (?i)password: "MySekretPa$$word"
#   # you don't want to show passwords in your logs
#   no_log: false
#
# - name: Force all notified handlers to run at this point, not waiting for normal sync points
#   meta: flush_handlers

# - include: getent.yml
#   tags:
#     - getent
#
# - include: core.yml
#   tags:
#     - core

# - name: install qemu
#   ansible.builtin.package:
#     name: "{{ qemu_packages }}"
#     state: present
#
# - name: wait for port to be available
#   ansible.builtin.wait_for:
#     port: "{{ ansible_port | default('22') }}"
#     timeout: "{{ sudo_timeout }}"
#   become: no
#   when:
#     - ansible_connection is defined
#     - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
#     - sudo_wait_for_host | bool

# - include: sudo.yml
#   tags:
#     - sudo

# - name: install buildtools
#   ansible.builtin.package:
#     name: "{{ buildtools_packages }}"
#     state: present

# - include: powertools.yml
#   tags:
#     - powertools
#
# - include_role:
#     name: buluma.core_dependencies
#
# - import_role:
#     name: buluma.buildtools

# - import_role:
#     name: buluma.systemd
- include: forensics.yml
  tags:
    - forensics
