---

- name: enable powertools
  community.general.ini_file:
    path: "{{ powertools_repo_path }}"
    section: powertools
    option: enabled
    value: "1"
    mode: "0644"
  notify:
    - yum update cache
  when:
    - ansible_distribution in [ "CentOS", "EL", "Rocky", "AlmaLinux" ]
    - ansible_distribution_major_version >= "8"
