---

- name: wait for port to be available
  ansible.builtin.wait_for:
    port: "{{ ansible_port | default('22') }}"
    timeout: "{{ sudo_timeout }}"
  become: no
  when:
    - ansible_connection is defined
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
    - sudo_wait_for_host | bool

- name: prepare system
  block:
    - name: test connection | sudo
      ansible.builtin.wait_for_connection:
        timeout: "{{ sudo_timeout }}"
      register: sudo_connect
      changed_when: no
  rescue:
    - name: gather sudo facts
      ansible.builtin.include_tasks:
        file: gather_facts.yml

    - name: install sudo packages (raw)
      ansible.builtin.raw: "{{ sudo_install.raw }}"
      register: sudo_install_packages
      changed_when:
        - (sudo_install.stdout_regex in sudo_install_packages.stdout and
           sudo_os_family in [ "Alpine", "Archlinux", "Gentoo" ]) or
          (sudo_install.stdout_regex not in sudo_install_packages.stdout and
           sudo_os_family in [ "Debian", "RedHat", "Rocky", "Suse" ])
  become: no
