---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-testing
      facts:
        - key: datacenter
          value: Nairobi
        - key: availability_zone
          value: west
