---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    # - role: buluma.systemd
    # # - name: buluma.python_pip
    # - role: buluma.sysctl
    - role: ansible-role-testing
      facts:
        - key: datacenter
          value: Nairobi
        - key: availability_zone
          value: west
