---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
driver:
  name: docker
platforms:
  - name: "testing-${image:-docker-centos7-ansible}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-docker-centos7-ansible}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
  enabled: False
  lint:
    name: flake8
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
